CREATE TABLE LOYALTYPOINTMOVEMENTS (
    MOVEMENTID INTEGER NOT NULL PRIMARY KEY,
    CUSTOMERID VARCHAR2(255),
    TRANSACTIONID VARCHAR2(255),
    ORDERID VARCHAR(255),
    ORDERNETVALUE NUMERIC(10,2),
    MOVEMENTDATE DATE,
    LOYALTYPOINTS INTEGER
    );
    
CREATE SEQUENCE LPMOVES_SEQ START WITH 1 INCREMENT BY 1;

SELECT * FROM LOYALTYPOINTMOVEMENTS;

INSERT INTO LOYALTYPOINTMOVEMENTS (MOVEMENTID, CUSTOMERID, TRANSACTIONID, ORDERID, ORDERNETVALUE, MOVEMENTDATE, LOYALTYPOINTS) 
VALUES (LPMOVES_SEQ.NEXTVAL, '0019283094','917832326492873', '019928497324', 239.35, TO_DATE('2018-02-19T08:40:51.620Z', 'yyyy-mm-dd hh24:mi:ss'), 7);
CREATE TABLE LOYALTYPOINTMOVEMENTS (
    MOVEMENTID INTEGER NOT NULL PRIMARY KEY,
    CUSTOMERID VARCHAR2(255),
    TRANSACTIONID VARCHAR2(255),
    ORDERID VARCHAR(255),
    ORDERNETVALUE NUMERIC(10,2),
    MOVEMENTDATE DATE,
    LOYALTYPOINTS INTEGER
    );
    
CREATE SEQUENCE LPMOVES_SEQ START WITH 1 INCREMENT BY 1;

SELECT * FROM LOYALTYPOINTMOVEMENTS;

INSERT INTO LOYALTYPOINTMOVEMENTS (MOVEMENTID, CUSTOMERID, TRANSACTIONID, ORDERID, ORDERNETVALUE, MOVEMENTDATE, LOYALTYPOINTS) 
VALUES (LPMOVES_SEQ.NEXTVAL, '0019283094','917832326492873', '019928497324', 239.35, TO_DATE('2018-01-09 08:40:51', 'yyyy/mm/dd hh24:mi:ss'), 7);

SELECT CIKEY,
  NODE_ID,
  SCOPE_ID,
  COUNT_ID,
  CREATION_DATE,
  CREATOR,
  MODIFY_DATE,
  MODIFIER,
  STATE,
  TRANSITION,
  EXCEPTION,
  EXP_DATE,
  EXP_FLAG,
  PRIORITY,
  LABEL,
  CUSTOM_ID,
  COMMENTS,
  REFERENCE_ID,
  IDEMPOTENT_FLAG,
  EXECUTION_TYPE,
  FIRST_DELAY,
  DELAY,
  EXT_STRING1,
  EXT_STRING2,
  EXT_INT1,
  CLUSTER_NODE_ID,
  VERSION,
  CI_PARTITION_DATE,
  CLUSTER_NODE_KEY
FROM DEV_SOAINFRA.WORK_ITEM  where CREATION_DATE > (sysdate - 7/24)
SELECT CIKEY,
  NODE_ID,
  SCOPE_ID,
  COUNT_ID,
  CREATION_DATE,
  CREATOR,
  MODIFY_DATE,
  MODIFIER,
  STATE,
  TRANSITION,
  EXCEPTION,
  EXP_DATE,
  EXP_FLAG,
  PRIORITY,
  LABEL,
  CUSTOM_ID,
  COMMENTS,
  REFERENCE_ID,
  IDEMPOTENT_FLAG,
  EXECUTION_TYPE,
  FIRST_DELAY,
  DELAY,
  EXT_STRING1,
  EXT_STRING2,
  EXT_INT1,
  CLUSTER_NODE_ID,
  VERSION,
  CI_PARTITION_DATE,
  CLUSTER_NODE_KEY
FROM DEV_SOAINFRA.WORK_ITEM  where CREATION_DATE > (sysdate - 30/60*1/24)

SELECT * FROM LOYALTYPOINTMOVEMENTS 
WHERE 
    CUSTOMERID='0019283094' 
    AND 
    MOVEMENTDATE >= TO_DATE('1970-01-01 00:00:00', 'YYYY-MM-DD HH:MM:SS') 
    AND 
    MOVEMENTDATE <= TO_DATE('2018-01-10 00:00:00', 'YYYY-MM-DD HH:MM:SS')


SELECT TO_DATE('2015/05/15 8:30:25', 'YYYY/MM/DD HH:MI:SS') 
FROM dual;

SELECT CUSTOMERID, SUM(LOYALTYPOINTS) AS BALANCE FROM LOYALTYPOINTMOVEMENTS WHERE MOVEMENTDATE <= TO_DATE('2018-01-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS') GROUP BY CUSTOMERID;


SELECT * FROM LOYALTYPOINTMOVEMENTS WHERE ORDERID = '124'